---
title: "Lab_7_Answers"
author: "Abbe LaBella"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reader)
library(ggplot2)
```


```{r data generation}


population1<-rnorm(30, mean=42, sd=4)
population2<-rnorm(30, mean=50, sd=4)
population3<-rnorm(30, mean=50, sd=5)
hist(c(population1,population2,population3))


pops<-c(rep("Midwest",30),rep("Eastern",30),rep("Western",30))

freqs<-c(population1,population2,population3)

rs12_frequency<-cbind(pops,freqs)
colnames(rs12_frequency)<-c("city_location","rs12_frequency")
rs12_frequency<-as.data.frame(rs12_frequency)

rs12_frequency$rs12_frequency<-as.numeric(rs12_frequency$rs12_frequency)
shapiro.test(rs12_frequency$rs12_frequency)

#write.table(rs12_frequency, file="rs12_frequency.csv",quote=F, sep=",")

```

```{r read in data}

rs12_frequency<-read.delim("rs12_frequency.csv", sep=",")

```

```{r Question Set A}

hist(rs12_frequency$rs12_frequency)
mean(rs12_frequency$rs12_frequency)


```

```{r Question Set B}

prior_prob<-c(rep((0.5/4),4),0.25,0.25)
sum(prior_prob)
prior_prob

val<-rs12_frequency$rs12_frequency[2]

normalF <- function(dat,mu,stdd) {
  # Likelihood of a normal distribution
  # dat - input data
  # mu - mean
  # stdd - standard deviation 
  sum((1/(sqrt(2*pi*stdd)))*exp(-(((dat-mu)^2)/(2*stdd^2))))
}

normalF(val, 50, 30)
#normalF(obs, 50,30)

```

```{r Question Set C}
lik = rep(0, 6)
obs<-rs12_frequency$rs12_frequency
mus<-c(44,46,48,50,52,54)
 
for(i in 1:length(mus)){
  lik[i]<- normalF(obs, mus[i], 30)
}
lik 


lik[4]

prior_likelihood<-lik*prior_prob
 
posterior<-prior_likelihood/sum(prior_likelihood)
posterior

plot(x=mu, y=posterior)
plot(x=mu, y=lik)

sum(posterior[1:4])
sum(posterior[5:6])

```


```{r markov chain}

iter<-10000
proposed_theta<-20
current_theta<-20
accept<-c()




#proposed likelihood for a current theta of 20 
proposed_lik<-normalF(obs, current_theta, 30)
proposed_lik

dbeta((current_theta/100),2,2)  

this_current_joint<-proposed_lik * dbeta((current_theta/100),2,2)
                                              
this_current_joint


prior<-function(x){dbeta(x,2,2)}

ggplot()+geom_function(fun=prior)


for(l in 1:iter){
  #print(l)
  #If the current theta is 100 - you must go down
  if(current_theta == 100){
    proposed_theta<-current_theta - rnorm(1,0,sd=5)
 
  }else if(current_theta==0){
    proposed_theta<-current_theta + rnorm(1,0,sd=5)
  }else{
    #randomly choose a direction to go in
    direction<-rbinom(1,2,0.5)
    if(direction == 1){
      #If the direction is 1 then go up
      proposed_theta<-current_theta + rnorm(1,0,sd=5)
    }else{
      #If the direction is not 1 then go down
      proposed_theta<-current_theta - rnorm(1,0,sd=5)
    }
  }
     
  #If the proposed theta is >100, set it to 100
  if(proposed_theta > 100){
    proposed_theta<-1
  }
  if(proposed_theta < 0){
    proposed_theta<-0
  }
  #Get the proposed likelihood
  
  proposed_lik<-normalF(obs, proposed_theta, 30)
  
  this_proposed_joint<-proposed_lik*dbeta((proposed_lik/100),2,2)
  
  if((this_proposed_joint/this_current_joint)<1){
    movement<-rbinom(1,2,0.5)
    if(movement == 1){
      #still move
      current_theta<-proposed_theta
      this_current_joint<-this_proposed_joint
    }else{
      #don't move
      current_theta<-current_theta
      this_current_joint<-this_current_joint
    }
  }else{
    #if it's larger we move
    current_theta<-proposed_theta
    this_current_joint<-this_proposed_joint
    }
    accept[l]<-current_theta
}


accept<-as.data.frame(cbind(accept, c(1:length(accept))))
ggplot(accept)+geom_histogram(aes(accept), bins=100)
ggplot(accept,aes(V2, accept))+geom_point()+geom_line()

mean(accept$accept)



```